package surface

func init() {
	MCPTools = append(MCPTools,
		Tool{Name: "brain.note.parse", Description: "Parse a brain note from the configured work/private vault and return structured content plus source-path metadata.", Required: []string{"sphere", "path"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Note path, relative to the brain root or absolute inside the vault."},
		}},
		Tool{Name: "brain.note.validate", Description: "Validate a brain note from the configured work/private vault and return structured diagnostics plus source-path metadata.", Required: []string{"sphere", "path"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Note path, relative to the brain root or absolute inside the vault."},
		}},
		Tool{Name: "brain.note.write", Description: "Round-trip safe update of a brain note's front matter and sections.", Required: []string{"sphere", "path", "fields"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Note path, relative to the brain root or absolute inside the vault."},
			"fields":      {Type: "object", Description: "Front matter and section updates. Use frontmatter and sections nested objects when you need to group fields."},
		}},
		Tool{Name: "brain.vault.validate", Description: "Validate every Markdown brain note in a configured vault and return diagnostics with source paths.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
		}},
		Tool{Name: "brain.links.resolve", Description: "Resolve a link safely inside a configured brain vault and return the resolved source path.", Required: []string{"sphere", "path", "link"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Source note path, relative to the brain root or absolute inside the vault."},
			"link":        {Type: "string", Description: "Link text to resolve."},
		}},
		Tool{Name: "brain.config.get", Description: "Return the active brain vault configuration and resolved vault roots.", Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
		}},
		Tool{Name: "brain.vault.list", Description: "Return the configured work and private vault roots.", Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
		}},
		Tool{Name: "brain.folder.parse", Description: "Parse a folder note from the configured work/private vault and return structured content plus source-path metadata.", Required: []string{"sphere", "path"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Note path, relative to the brain root or absolute inside the vault."},
		}},
		Tool{Name: "brain.folder.validate", Description: "Validate a folder note from the configured work/private vault and return structured diagnostics plus source-path metadata.", Required: []string{"sphere", "path"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Note path, relative to the brain root or absolute inside the vault."},
		}},
		Tool{Name: "brain.folder.links", Description: "Extract folder note links from the configured work/private vault and return source-path metadata.", Required: []string{"sphere", "path"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Note path, relative to the brain root or absolute inside the vault."},
		}},
		Tool{Name: "brain.folder.audit", Description: "Audit every folder note in a configured vault and return diagnostics with source paths.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
		}},
		Tool{Name: "brain.glossary.parse", Description: "Parse a glossary note from the configured work/private vault and return structured content plus source-path metadata.", Required: []string{"sphere", "path"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Note path, relative to the brain root or absolute inside the vault."},
		}},
		Tool{Name: "brain.glossary.validate", Description: "Validate a glossary note from the configured work/private vault and return structured diagnostics plus source-path metadata.", Required: []string{"sphere", "path"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Note path, relative to the brain root or absolute inside the vault."},
		}},
		Tool{Name: "brain.attention.parse", Description: "Parse an attention note from the configured work/private vault and return structured content plus source-path metadata.", Required: []string{"sphere", "path"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Note path, relative to the brain root or absolute inside the vault."},
		}},
		Tool{Name: "brain.attention.validate", Description: "Validate an attention note from the configured work/private vault and return structured diagnostics plus source-path metadata.", Required: []string{"sphere", "path"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Note path, relative to the brain root or absolute inside the vault."},
		}},
		Tool{Name: "brain.entities.candidates", Description: "Extract deterministic entity candidates from reviewed notes in a configured vault.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"limit":       {Type: "integer", Description: "Maximum candidates to return."},
		}},
		Tool{Name: "brain.gtd.parse", Description: "Parse every GTD commitment note in a configured vault and return structured content plus source-path metadata.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
		}},
		Tool{Name: "brain.gtd.list", Description: "Return a filtered GTD commitment list from a configured vault.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"status":      {Type: "string", Description: "Optional status filter."},
			"person":      {Type: "string", Description: "Optional person filter."},
			"project":     {Type: "string", Description: "Optional project filter."},
			"track":       {Type: "string", Description: "Optional attention track filter."},
			"source":      {Type: "string", Description: "Optional source filter."},
			"limit":       {Type: "integer", Description: "Maximum results to return."},
		}},
		Tool{Name: "brain.gtd.write", Description: "Round-trip safe create or update of a GTD commitment note.", Required: []string{"sphere", "path", "commitment"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Commitment note path to create or update."},
			"commitment":  {Type: "object", Description: "Commitment field updates. Missing fields preserve their current values."},
		}},
		Tool{Name: "brain.gtd.organize", Description: "Generate an organized GTD index note for a vault sphere.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Optional output note path. Defaults to brain/gtd/organize.md."},
		}},
		Tool{Name: "brain.gtd.resurface", Description: "Promote deferred commitments whose follow-up date has arrived back to next.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"path":        {Type: "string", Description: "Optional commitment path to resurface. When omitted, the whole vault is scanned."},
		}},
		Tool{Name: "brain.gtd.dashboard", Description: "Generate a GTD dashboard note for one named person or subject. Renders a WIP table for any tracks with wip_limit configured in gtd.toml.", Required: []string{"sphere", "name"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"gtd_config":  {Type: "string", Description: "Optional GTD config path with per-track wip_limit. Defaults to ~/.config/sloptools/gtd.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"name":        {Type: "string", Description: "Dashboard subject name."},
			"path":        {Type: "string", Description: "Optional output note path. Defaults to brain/gtd/dashboards/<slug>.md."},
		}},
		Tool{Name: "brain.gtd.today", Description: "Generate or read the closed daily list (<= 8 items) for one date. Items added after the day's list is generated do not appear until the next day.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path":          {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":               {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"date":                 {Type: "string", Description: "Optional date (YYYY-MM-DD or RFC3339). Defaults to today UTC."},
			"pinned_paths":         {Type: "array", Description: "Optional commitment paths that must appear first."},
			"include_family_floor": {Type: "boolean", Description: "When true, pre-fill remaining slots with track/core (focus: core) commitments before filler."},
			"limit":                {Type: "integer", Description: "Optional cap (1-8). Hard cap is 8."},
			"refresh":              {Type: "boolean", Description: "Regenerate today's list, replacing any persisted closed list for this date."},
			"sources":              {Type: "array", Description: "Optional review_list sources passed through to the underlying query."},
			"project_dirs":         {Type: "array", Description: "Optional Git checkout directories for GitHub/GitLab issue and PR sources."},
		}},
		Tool{Name: "brain.gtd.review_batch", Description: "Generate a Markdown review batch from GTD items selected by deterministic review signals and optional query matching.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"q":           {Type: "string", Description: "Review query."},
			"track":       {Type: "string", Description: "Optional attention track filter; also supplies the query when q is omitted."},
			"path":        {Type: "string", Description: "Optional output note path. Defaults to brain/gtd/reviews/<slug>.md."},
		}},
		Tool{Name: "brain.gtd.ingest", Description: "Ingest source notes into GTD commitment notes. For source=meetings, paths can be omitted to walk the configured meetings_root.", Required: []string{"sphere", "source"}, Properties: map[string]ToolProperty{
			"config_path":    {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":         {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
			"source":         {Type: "string", Description: "Ingest source name. Initial support: meetings, mail, todoist, github, gitlab, evernote."},
			"paths":          {Type: "array", Description: "Source note paths to ingest. Optional for source=meetings when meetings_root is configured."},
			"path":           {Type: "string", Description: "Alias for a single source path."},
			"sources_config": {Type: "string", Description: "Optional sources/meetings config path. Defaults to ~/.config/sloptools/sources.toml."},
		}},
		Tool{Name: "brain.search", Description: "Search a configured brain vault with rg-backed exact, regex, link, or alias matching.", Required: []string{"sphere", "query"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to search.", Enum: []string{"work", "private"}},
			"query":       {Type: "string", Description: "Search query."},
			"mode":        {Type: "string", Description: "Search mode.", Enum: []string{"text", "regex", "wikilink", "markdown_link", "alias"}},
			"limit":       {Type: "integer", Description: "Maximum results to return. Defaults to 50."},
		}},
		Tool{Name: "brain.backlinks", Description: "Find Markdown and wikilink backlinks to a note in a configured brain vault.", Required: []string{"sphere", "target"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to search.", Enum: []string{"work", "private"}},
			"target":      {Type: "string", Description: "Target note path, relative to the brain root or absolute inside the vault."},
			"limit":       {Type: "integer", Description: "Maximum results to return. Defaults to 50."},
		}},
		Tool{Name: "brain.gtd.bind", Description: "Attach source bindings to a GTD commitment or collapse same-outcome commitments into one local aggregate overlay.", Required: []string{"sphere", "winner_path"}, Properties: map[string]ToolProperty{
			"config_path":     {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":          {Type: "string", Description: "Vault sphere to update.", Enum: []string{"work", "private"}},
			"winner_path":     {Type: "string", Description: "Commitment path whose outcome and local overlay survive."},
			"paths":           {Type: "array", Description: "Commitment paths to bind. Same-outcome non-winners become equivalent to winner."},
			"outcome":         {Type: "string", Description: "Optional winning outcome text."},
			"source_bindings": {Type: "array", Description: "Optional source binding objects with provider/ref to attach to the winner."},
		}},
		Tool{Name: "brain.gtd.dedup_scan", Description: "Reconcile GTD commitments by stable source binding and return non-destructive duplicate review candidates.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path":             {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":                  {Type: "string", Description: "Vault sphere to scan.", Enum: []string{"work", "private"}},
			"dedup_config":            {Type: "string", Description: "Optional per-user TOML with dedup thresholds and local LLM command."},
			"deterministic_threshold": {Type: "number", Description: "Optional deterministic candidate threshold."},
			"llm_threshold":           {Type: "number", Description: "Optional deterministic score threshold before local LLM review."},
			"candidate_threshold":     {Type: "number", Description: "Optional LLM confidence threshold for review candidates."},
			"llm_command":             {Type: "string", Description: "Optional local command that reads a JSON prompt on stdin and emits JSON."},
		}},
		Tool{Name: "brain.gtd.dedup_review_apply", Description: "Apply a user dedup decision without mutating upstream sources.", Required: []string{"sphere", "id", "decision"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to update.", Enum: []string{"work", "private"}},
			"id":          {Type: "string", Description: "Candidate id returned by brain.gtd.dedup_scan."},
			"decision":    {Type: "string", Description: "Review decision.", Enum: []string{"merge", "keep_separate", "defer"}},
			"winner_path": {Type: "string", Description: "For merge, commitment path whose outcome text survives."},
			"outcome":     {Type: "string", Description: "For merge, optional winning outcome text."},
		}},
		Tool{Name: "brain.gtd.dedup_history", Description: "Return durable GTD dedup decisions stored in commitment front matter.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path": {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sphere":      {Type: "string", Description: "Vault sphere to inspect.", Enum: []string{"work", "private"}},
		}},
		Tool{Name: "brain.gtd.review_list", Description: "Return a normalized GTD review list across Markdown commitments, task providers, and issue sources without materializing duplicate Markdown notes. The response includes an over_wip slice of tracks whose open next count exceeds the wip_limit configured in gtd.toml.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path":      {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"gtd_config":       {Type: "string", Description: "Optional GTD config path with per-track wip_limit. Defaults to ~/.config/sloptools/gtd.toml."},
			"sphere":           {Type: "string", Description: "Vault/account sphere to inspect.", Enum: []string{"work", "private"}},
			"sources":          {Type: "array", Description: "Optional source classes. Defaults to markdown,mail,github,gitlab. tasks/todoist/google_tasks/evernote remain accepted but emit a deprecation warning when explicit."},
			"account_id":       {Type: "integer", Description: "Optional tasks-capable account id for task-backed items."},
			"list_ids":         {Type: "array", Description: "Optional task list/project ids to scan. Defaults to all lists."},
			"project_dirs":     {Type: "array", Description: "Optional Git checkout directories for GitHub/GitLab issue and PR sources."},
			"provider":         {Type: "string", Description: "Optional issue provider override for project_dirs.", Enum: []string{"auto", "github", "gitlab"}},
			"queue":            {Type: "string", Description: "Optional GTD queue filter.", Enum: []string{"inbox", "next", "waiting", "deferred", "review", "someday", "done"}},
			"project":          {Type: "string", Description: "Optional project/list/outcome filter."},
			"track":            {Type: "string", Description: "Optional attention track filter."},
			"due_before":       {Type: "string", Description: "Optional inclusive due upper bound, RFC3339 or YYYY-MM-DD."},
			"due_after":        {Type: "string", Description: "Optional inclusive due lower bound, RFC3339 or YYYY-MM-DD."},
			"follow_up_before": {Type: "string", Description: "Optional inclusive follow-up/start upper bound, RFC3339 or YYYY-MM-DD."},
			"follow_up_after":  {Type: "string", Description: "Optional inclusive follow-up/start lower bound, RFC3339 or YYYY-MM-DD."},
			"limit":            {Type: "integer", Description: "Optional maximum number of normalized items to return."},
		}},
		Tool{Name: "brain.gtd.set_status", Description: "Set a commitment local overlay status, then automatically reconcile writeable source bindings from sources.toml.", Required: []string{"sphere", "path", "status"}, Properties: map[string]ToolProperty{
			"config_path":     {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sources_config":  {Type: "string", Description: "Optional source writeability config path. Defaults to ~/.config/sloptools/sources.toml."},
			"sphere":          {Type: "string", Description: "Vault sphere to update.", Enum: []string{"work", "private"}},
			"path":            {Type: "string", Description: "Commitment note path."},
			"commitment_id":   {Type: "string", Description: "Alias for path."},
			"status":          {Type: "string", Description: "Local overlay status to set."},
			"closed_at":       {Type: "string", Description: "Optional RFC3339 closed timestamp for closed statuses."},
			"closed_via":      {Type: "string", Description: "Optional closure source label. Defaults to brain.gtd.set_status."},
			"mail_action":     {Type: "string", Description: "Mail action for closed mail bindings. Defaults to archive."},
			"mail_label":      {Type: "string", Description: "Optional label for label-based mail actions."},
			"mail_folder":     {Type: "string", Description: "Optional folder for folder-based mail actions."},
			"todoist_list_id": {Type: "string", Description: "Optional Todoist project/list id when the binding ref does not include one."},
		}},
		Tool{Name: "brain.gtd.sync", Description: "Reconcile writeable GTD source bindings by pushing closed local overlays upstream or pulling periodic upstream closure state down.", Required: []string{"sphere"}, Properties: map[string]ToolProperty{
			"config_path":     {Type: "string", Description: "Optional vault config path. Defaults to ~/.config/sloptools/vaults.toml."},
			"sources_config":  {Type: "string", Description: "Optional source writeability config path. Defaults to ~/.config/sloptools/sources.toml."},
			"sphere":          {Type: "string", Description: "Vault sphere to sync.", Enum: []string{"work", "private"}},
			"path":            {Type: "string", Description: "Optional commitment note path. When omitted, every commitment in the sphere is scanned."},
			"commitment_id":   {Type: "string", Description: "Alias for path."},
			"periodic":        {Type: "boolean", Description: "When true, read upstream state and pull closed state into the local overlay."},
			"dry_run":         {Type: "boolean", Description: "Report actions without applying upstream or Markdown writes."},
			"mail_action":     {Type: "string", Description: "Mail action for closed mail bindings. Defaults to archive."},
			"mail_label":      {Type: "string", Description: "Optional label for label-based mail actions."},
			"mail_folder":     {Type: "string", Description: "Optional folder for folder-based mail actions."},
			"todoist_list_id": {Type: "string", Description: "Optional Todoist project/list id when the binding ref does not include one."},
		}},
	)
}
